name: practice

on:
  push:
    branches: 
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push Repo
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python -m pip install --upgrade pip
      - run: pip install -r requierments.txt